# See https://redocly.com/docs/cli/configuration/ for more information.
apis:
  sample@v1: 
    root: api/google.yaml
lint:
  extends:
    - recommended
  rules:
    no-unused-components: error
    operation-operationId: off
    spec: off