name: Apple OpenAPI Validation
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Apple OpenAPI Lint Checks
        uses: mcastany/openapi-action@1.0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          file: api/google.json
          title: 'Apple OpenAPI Lint Checks'