name: GitHub Actions Demo
on:
  push:
    branches:
      - feature/*
jobs:
  validate_api:
    runs-on: ubuntu-latest
    steps:
      - name: OpenAPI Lint Checks
        uses: nwestfall/openapi-action@v1.0.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          file: FILE_PATH